[[getting_started]]
= Getting Started

CAUTION: You need Java 8 or newer and JavaFX in order to use Text-IO.

Text-IO is available in Maven Central and JCenter.


|===
|Maven |Gradle

a| [subs="attributes",options="nowrap"]
----
&lt;dependency&gt;
    &lt;groupId&gt;{project-group}&lt;/groupId&gt;
    &lt;artifactId&gt;text-io&lt;/artifactId&gt;
    &lt;version&gt;{project-version}&lt;/version&gt;
&lt;/dependency&gt;
----

a| [subs="attributes",options="nowrap"]
----
compile '{project-group}:text-io:{project-version}'
----
|===

{nbsp} +

In order to use the link:javadoc/org/beryx/textio/web/WebTextTerminal.html[WebTextTerminal],
you have to include the `text-io-web` artifact:
|===
|Maven |Gradle

a| [subs="attributes",options="nowrap"]
----
&lt;dependency&gt;
    &lt;groupId&gt;{project-group}&lt;/groupId&gt;
    &lt;artifactId&gt;text-io-web&lt;/artifactId&gt;
    &lt;version&gt;{project-version}&lt;/version&gt;
&lt;/dependency&gt;
----

a| [subs="attributes",options="nowrap"]
----
compile '{project-group}:text-io-web:{project-version}'
----
|===

Additionally, you have to include the artifacts needed by the link:javadoc/org/beryx/textio/web/DataServer.html[DataServer] implementation you want to use.

For link:javadoc/org/beryx/textio/web/RatpackDataServer.html[RatpackDataServer]:
|===
|Maven |Gradle

a| [subs="attributes",options="nowrap"]
----
&lt;dependency&gt;
    &lt;groupId&gt;io.ratpack&lt;/groupId&gt;
    &lt;artifactId&gt;ratpack-core&lt;/artifactId&gt;
    &lt;version&gt;1.5.1&lt;/version&gt;
&lt;/dependency&gt;
&lt;dependency&gt;
    &lt;groupId&gt;io.ratpack&lt;/groupId&gt;
    &lt;artifactId&gt;ratpack-session&lt;/artifactId&gt;
    &lt;version&gt;1.5.1&lt;/version&gt;
&lt;/dependency&gt;
----

a| [subs="attributes",options="nowrap"]
----
compile 'io.ratpack:ratpack-core:1.5.1'
compile 'io.ratpack:ratpack-session:1.5.1'
----
|===

For link:javadoc/org/beryx/textio/web/SparkDataServer.html[SparkDataServer]:
|===
|Maven |Gradle

a| [subs="attributes",options="nowrap"]
----
&lt;dependency&gt;
    &lt;groupId&gt;com.sparkjava&lt;/groupId&gt;
    &lt;artifactId&gt;spark-core&lt;/artifactId&gt;
    &lt;version&gt;2.7.1&lt;/version&gt;
&lt;/dependency&gt;
----

a| [subs="attributes",options="nowrap"]
----
compile 'com.sparkjava:spark-core:2.7.1'
----
|===
